###
GET http://localhost:3000/filmes

###
POST http://localhost:3000/filmes
Content-Type: application/json

{
 "titulo": "Gremlins",
 "genero": "Comédia",
 "ano_lancamento": "1984",
 "diretor": "Joe Dante"
}
###
PUT http://localhost:3000/filmes/
Content-Type: application/json

{
 "nome": "Marcos",
 "senha": "leaf green"
}
###
DELETE http://localhost:3000/filmes/